
name: Make

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true

      # Set up a matrix to run the following 3 configurations:
      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      # 3. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
      #
      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        c_compiler: [gcc, clang]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure
      run: | #>
        sudo apt-get install gettext -y


        
 #       sudo apt-get install autoconf 


    - name: Make
      id: string
      run: |
        make
        echo "make success"

    - name: TEST
      run: |
        tree
        ls
        sudo make install
        
      # echo "start deb build"
        # debuild -us -uc
        # echo "start rpm build"
        # rpmbuild -ba mentohust.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mentohust-${{ matrix.os }}-${{ matrix.version }}
        path: ./mentohust  # 请根据你实际编译后文件的路径进行修改
